name: Release

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # 1. Setup Phase
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full git history for changesets
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      # 2. Changeset Phase
      - name: Store Changeset Info
        run: |
          mkdir -p ./temp
          cp -r .changeset ./temp/

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          commit: "chore: version packages"
          title: "chore: version packages"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 3. GitHub Release Phase
      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        run: |
          cp -r ./temp/.changeset .
          npm run create-github-release
          rm -rf ./temp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
